@startuml

== prepare ==
main --> fs: read and validate configuration file
note right: read from disk\n\
load structure
main --> docker: validate docker configuration against GAR
note right: docker login?\n\
docker pull <well-known>?\n\
check file .docker/config.json?\n\
gcloud active user is *@nav.no?\n\
gcloud API calls work?
main --> fs: collect build, publish and deploy parameters
note right: detect SDK\n\
detect SDK parameters\n\
read secrets
main --> sdk: detect and validate build target
note right: build dependency graph

== build/docker ==
main --> sdk: determine image name
note right: HOST/TEAM/APP:VERSION
main --> sdk: determine tag/version
note right: datestamp + git sha
main --> sdk: generate multi-stage dockerfile
note right: \
determine base image for builder\n\
define any mid-stage base builders\n\
determine final base image
main --> sdk: build image
main --> slsa: generate signature and attestation
note right: run asynchronously to reduce build time?

== publish/gar ==
main --> gar: upload docker image
main --> gar: upload signature and attestation

== publish/github ==
main --> github: create release in repo
main --> github: upload assets

== deploy/nais ==
main --> sdk: render yaml templates
main --> sdk: generate deploy metadata
main --> deploy: deploy application

== deploy/cdn ==
main --> main: determine destination directory
main --> cdn: upload directory

@enduml
