@startuml

== prepare ==
main --> fs: read and validate configuration file
main --> main: determine outputs
main --> main: validate build graph
main --> fs: collect build, publish and deploy parameters
main --> sdk: detect and validate build target

== build/docker ==
main --> main: determine image name
main --> main: determine tag/version
main --> sdk: generate multi-stage dockerfile
sdk --> sdk: determine base image for builder
sdk --> sdk: detect any mid-stage base builders
sdk --> sdk: determine final base image
main --> main: run docker build
main --> slsa: generate signature and attestation

== publish/gar ==
main --> gar: upload docker image
main --> gar: upload signature and attestation

== publish/github ==
main --> github: create release in repo
main --> github: upload assets

== deploy/nais ==
main --> main: assemble metadata
main --> main: insert variables into nais.yaml
main --> deploy: run deploy

== deploy/cdn ==
main --> main: determine destination directory
main --> cdn: upload directory

@enduml
